### ISSUE TITLE
Move project to Weld for easier maintenance and lower risk of breaking app due to dependencies change

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans-config-api#33]
Move project to Weld for easier maintenance and lower risk of breaking app due to dependencies change

**Comment by yuriyz** [comment]
We should use same stack of frameworks as used in jans-auth-server. jans-config-api will run under jetty.

**Comment by pujavs** [comment]
High Level Changes:

1) Remove dependency to Quarkus libraries
2) Using Weld for CDI - to be in sync will refer existing jans project
3) Changing to maven modules app(main), auth(existing code for auth server api). Likewise, modules can be created for other api as needed

**Comment by pujavs** [comment]
[Quarkus_Removal_Issues.txt](https://github.com/JanssenProject/jans-config-api/files/6428251/Quarkus_Removal_Issues.txt)

**Comment by yuriyz** [comment]
Try to remove `org.glassfish.jersey.bundles:jaxrs-ri:jar:2.29:compile`. In general idea is to add only required dependencies. We don't want to mess class path.

**Comment by pujavs** [comment]
Able to locally test  GET endpoints
[Jan-Config_Api_Testing.xlsx](https://github.com/JanssenProject/jans-config-api/files/6442940/Jan-Config_Api_Testing.xlsx)

API Protection not working as WELD not able to instantiate the ContainerRequestContext Filter

**Comment by pujavs** [comment]
Issue wrt ContainerRequestContext Filter resolved and code now working with API Protection 

[Jan-Config_Api_Testing_With_oAuth.xlsx](https://github.com/JanssenProject/jans-config-api/files/6465605/Jan-Config_Api_Testing_With_oAuth.xlsx)

**Comment by pujavs** [comment]
Json patch not working -> Analyzing

**Comment by pujavs** [comment]
Karate test cases of weld migrated jans-config-api 
[surefire-reports.zip](https://github.com/JanssenProject/jans-config-api/files/6473177/surefire-reports.zip)

**Comment by pujavs** [comment]
Removed all quarkus dependencies and used weld for CDI.
**Issues faced** :  JSON PATCH endpoint not working due to incompatible jans-auth-server and jans-client resteasy version  3.14.0.Final
**Analysis:** 
Json patch does not work with resteasy version 3.14.0.Final, for Json patch to work we need resteasy version 4.5.6.Final
All versions from 3.14.0.Final till 4.5.6.Final verified. Working with 4.5.6.Final version
1) restsample_4.5.6_Json_Patch_Working.zip  - [restsample_4.5.6_Json_Patch_Working.zip](https://github.com/JanssenProject/jans-config-api/files/6733319/restsample_4.5.6_Json_Patch_Working.zip)
2) restsample_3.14.0_Json_Patch_Not_Working.zip - [restsample_3.14.0_Json_Patch_Not_Working.zip](https://github.com/JanssenProject/jans-config-api/files/6733318/restsample_3.14.0_Json_Patch_Not_Working.zip)
**Analysed approaches:**
Approach#1: If using resteasy dependency version same as jans-auth-server then using Json patch with MediaType.APPLICATION_JSON_PATCH_JSON -> “application/json-patch+json gives 415 - Unsupported Media Type error
Approach#2: If we exclude resteasy (3.14.0.Final) from jans dependency and use the latest resteasy version(4.5.6.Final) than we will have to write the jans auth client again like in Quarkus
Approach#3: Upgrade resteasy versions in all jans-auth and other jans-client to latest, 4.5.6.Final or above
**Final Implementation:**
Approach#2 from above -> Upgraded resteasy version 4.5.6.Final in jans-config-api. Since 4.5.6.Final is not compatible with existing jans-auth and jans-client hence created the resteasy client for introspection in jans-config-api. This is same as used in Quarkus.

**Comment by pujavs** [comment]
Tested and enabled jenkins build for the jetty base jans-config-api 
https://jenkins.jans.io/jenkins/job/jans-config-api/939/cucumber-html-reports_393f3d47-d30d-3acf-a82f-41b0e41e87bb/overview-features.html

![image](https://user-images.githubusercontent.com/43700552/125961716-4bc36fdd-d6d6-4e20-87c7-37a1705e04cf.png)
