### ISSUE TITLE
Provide endpoints for config api roles management

### ISSUE THREAD

**Issue by syntrydy** [JanssenProject/jans-config-api#51]
### User Story Title.

Implement endpoints for config API roles and permissions management

### User Story Meta Information.

This should be base on the existing config API roles/permissions

#### Priority.

 MEDIUM

### Description.

As an API consumer with the roles/permissions management permission set, I should be able to: 
 
- List all config API roles
- List all config API permissions
- Add/Edit/View/Remove API role
- Add/Edit/View/Remove API permission
- Assign/Unassign permission to API role

**Comment by duttarnab** [comment]
Hi @nynymike 

https://github.com/GluuFederation/gluu-admin-ui/wiki/Janssen-Admin-UI----Application-Architecture#generating-api-protection-token-at2-and-enablingdisabling-features-at-frontend

In `admin-ui` we used external auth-server (`jans-auth-server-2`) to generate config-api `protection-token` . In `jans-auth-server-2` we store `role-scope` mapping in interception script, to add the scopes (based on `admin-ui` role) in the `protection-token`.

Can we manage this `role-scope` mapping in `jans-auth-server-1` so that it can be managed by `administrator` using `admin-ui`?

**Comment by nynymike** [comment]
We cannot assume that auth-server-1 is the server that holds the users who have admin rights on auth-server-1.

**Comment by duttarnab** [comment]
Done
